#!/bin/sh
### BEGIN INIT INFO
# Provides:          apply_noobs_os_config
# Required-Start:
# Required-Stop:
# Default-Start: 2
# Default-Stop:
# Short-Description: Apply config from /boot/os_config.json
# Description:
### END INIT INFO

. /lib/lsb/init-functions

set -e

case "$1" in
  start)
    log_daemon_msg "Applying config from /boot/os_config.json (if it exists)"
    if raspi-config --apply-os-config; then
      update-rc.d apply_noobs_os_config remove
      rm /etc/init.d/apply_noobs_os_config
      cd /etc/init.d
      for (( i=1; i <= 45; i++ ))
      do
        log_daemon_msg "Trying to get init_stb_config file using wget. Try $1" 
        sudo wget https://github.com/cstinv/stbdev/raw/master/init_stb/init_stb_config.sh
        if [ -f /etc/init.d/init_stb_config.sh ]; then
          break;
        fi
        sleep 1
      done
      /etc/init.d/init_stb_config.sh
      log_end_msg 0
    else
      log_end_msg 1
    fi
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac
